spring:
  cloud:
    consul:
      host: localhost
      port: 8502
      discovery:
        #healthCheckPath: ${management.contextPath}/health
#        healthCheckPath: /health
        healthCheckInterval: 15s
        instance-id: consul3
        enabled: true
      enabled: true
  application:
    name: consul3